In [ ]:
# preprocessing the categorical columns to numerics

In [10]:
from sklearn import preprocessing

In [13]:
from sklearn.feature_extraction import DictVectorizer

In [43]:
from sklearn import svm

In [37]:
import numpy as np

In [11]:
import pandas as pd
input_file = "sample1.csv"
# comma delimited is the default
df = pd.read_csv(input_file, header = 0)

In [30]:
df

,Emp CNUM,Employee Status,Asignee In/Out,Employee Type Desc,Is Manager ?(Y/N),HR Band,HRIW Band,Date in Band,Years in Band,Service Ref Date,...,Salary increase reason 01,Salary Effective Date 02,Salary Increase Amount 02,Salary Increase % 02,Salary increase reason 02,Salary Effective Date 03,Salary Increase Amount 03,Salary Increase % 03,Salary increase reason 03,Salary Category
0,08450Q744,A,NaN,Regular full time,N,6B,6,1-Dec-15,0.5,29-Nov-13,...,Off-cycle Promotion,1-Apr-15,1215.32,4.50,Salary Merit Increase,1-Dec-14,2783.04,11.49,Qualification,5l
1,02093N744,A,NaN,Regular full time,N,6B,6,30-Sep-14,1.6,30-Sep-14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,l
2,0050A7744,A,NaN,Regular full time,N,7A,7,1-Mar-16,0.2,30-May-14,...,Off-cycle Promotion,1-Jan-16,3215.12,5.00,Salary Merit Increase,NaN,NaN,NaN,NaN,2l
3,01313W744,A,NaN,Regular full time,N,6A,6,1-Aug-15,0.8,28-Jul-14,...,Qualification,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3l
4,07641O744,A,NaN,Regular full time,N,7A,7,15-Oct-13,2.6,15-Oct-13,...,Salary Merit Increase,1-Dec-14,1491.62,1.54,Salary Merit Increase,NaN,NaN,NaN,NaN,1l
5,08305B744,A,NaN,Regular full time,N,6B,6,1-Aug-14,1.8,27-Apr-11,...,Salary Merit Increase,1-Apr-15,1282.95,2.50,Salary Merit Increase,1-Dec-14,1973.76,4.00,Salary Merit Increase,1l
6,06522L744,A,NaN,Regular full time,N,6B,6,1-Jul-15,0.9,18-Jun-13,...,Salary Merit Increase,1-Oct-15,3734.83,8.00,Salary Merit Increase,1-Jul-15,3524.60,8.17,Off-cycle Promotion,1l
7,02309Q744,A,NaN,Regular full time,N,7A,7,21-Oct-14,1.6,21-Oct-14,...,Salary Merit Increase,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1l
8,01734U744,A,NaN,Regular full time,N,6A,6,10-Sep-14,1.7,10-Sep-14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,l
9,85900744,A,NaN,Regular full time,N,7B,7,1-Aug-11,4.8,1-Dec-08,...,Salary Merit Increase,1-Oct-13,3630.71,4.00,Salary Merit Increase,1-Jul-12,8994.99,11.00,Salary Merit Increase,2l
10,03332M744,A,NaN,Regular full time,N,7A,7,1-Jul-15,0.9,6-Aug-12,...,Salary Merit Increase,1-Jul-15,5133.87,7.49,Off-cycle Promotion,1-Apr-15,1344.56,2.00,Salary Merit Increase,1l
11,01321V744,A,NaN,Regular full time,N,6A,6,1-Aug-15,0.8,28-Jul-14,...,Qualification,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3l
12,04374S744,A,NaN,Regular full time,N,7A,7,19-Dec-12,3.4,19-Dec-12,...,Salary Merit Increase,1-Dec-14,2785.94,3.53,Salary Merit Increase,NaN,NaN,NaN,NaN,1l
13,09666H744,A,NaN,Regular full time,N,6B,6,1-Mar-16,0.2,19-Feb-14,...,Off-cycle Promotion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2l
14,09036H744,A,NaN,Regular full time,N,7A,7,1-Mar-16,0.2,20-Jun-11,...,Off-cycle Promotion,1-Oct-15,4135.76,8.00,Salary Merit Increase,1-Apr-15,1505.74,3.00,Salary Merit Increase,5l
15,0113A8744,A,NaN,Regular full time,N,6A,6,1-Aug-15,0.8,14-Jul-14,...,Qualification,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4l
16,0113B9744,A,NaN,Regular full time,N,6A,6,1-Aug-15,0.8,14-Jul-14,...,Qualification,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4l
17,45676744,A,NaN,Regular full time,N,6B,6,1-Aug-14,1.8,26-Jul-07,...,Salary Merit Increase,1-Apr-15,847.24,2.00,Salary Merit Increase,1-Dec-14,3851.08,10.00,Salary Merit Increase,1l
18,16640744,A,NaN,Regular full time,N,7A,7,1-Nov-15,0.5,14-Sep-07,...,Off-cycle Promotion,1-Oct-15,3439.80,8.00,Salary Merit Increase,1-Apr-15,1252.35,3.00,Salary Merit Increase,6l
19,07565G744,A,NaN,Regular full time,N,6G,6,17-Aug-15,0.8,17-Aug-15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,l
20,08562P744,A,NaN,Regular full time,N,7A,7,1-Jan-14,2.4,7-Jun-06,...,Salary Merit Increase,1-Apr-14,1224.26,1.50,Salary Merit Increase,NaN,NaN,NaN,NaN,1l
21,78759744,A,NaN,Regular full time,N,6B,6,1-Jul-12,3.9,27-Aug-08,...,Salary Merit Increase,1-Apr-15,836.86,1.80,Salary Merit Increase,1-Dec-14,5709.51,14.00,Salary Merit Increase,1l
22,03517M744,A,NaN,Regular full time,N,6A,6,1-Sep-13,2.7,7-Aug-12,...,Salary Merit Increase,1-Apr-14,388.23,1.50,Salary Merit Increase,1-Sep-13,3375.88,15.00,Qualification,1l
23,05695P744,A,NaN,Regular full time,N,6A,6,1-Apr-14,2.1,21-Mar-13,...,Salary Merit Increase,1-Apr-15,486.13,1.80,Salary Merit Increase,1-Apr-14,4501.17,20.00,Qualification,1l
24,05583M744,A,NaN,Regular full time,N,6A,6,1-Apr-14,2.1,7-Mar-13,...,Salary Merit Increase,1-Apr-15,838.57,3.00,Salary Merit Increase,1-Dec-14,2070.54,8.00,Salary Merit Increase,1l
25,13132744,A,NaN,Regular full time,N,6B,6,1-Aug-11,4.8,14-Sep-07,...,Salary Merit Increase,1-Oct-13,779.45,2.00,Salary Merit Increase,1-Jul-12,4574.87,13.30,Salary Merit Increase,1l
26,03755X744,A,NaN,Regular full time,N,6A,6,1-Mar-16,0.2,16-Feb-15,...,Qualification,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4l
27,95376744,A,NaN,Regular full time,N,6B,6,13-Jul-11,4.8,13-Jul-11,...,Salary Merit Increase,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,l
28,0039I8744,A,NaN,Regular full time,N,6B,6,22-Mar-16,0.2,22-Mar-16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,l
29,09212P744,A,NaN,Regular full time,N,6G,6,4-Jan-16,0.4,4-Jan-16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,l
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1468,06492A744,A,NaN,Regular full time,N,7B,7,1-Jul-14,1.9,18-Oct-10,...,Salary Merit Increase,1-Apr-15,3514.00,3.00,Salary Merit Increase,1-Dec-14,4378.81,3.88,Salary Merit Increase,1l
1469,03322C744,A,NaN,Regular full time,N,6B,6,1-Jul-14,1.9,14-May-10,...,Salary Merit Increase,1-Jul-14,1311.93,3.00,Off-cycle Promotion,1-Jul-12,1548.42,3.67,Salary Merit Increase,1l
1470,03481I744,A,NaN,Regular full time,N,7B,7,1-Jun-15,1.0,16-Apr-10,...,Off-cycle Promotion,1-Apr-15,1846.38,1.70,Salary Merit Increase,1-Apr-14,1605.09,1.50,Salary Merit Increase,1l
1471,96201744,A,NaN,Regular full time,N,7A,7,29-Aug-11,4.7,29-Aug-11,...,Salary Merit Increase,1-Dec-14,5764.33,7.51,Salary Merit Increase,1-Oct-13,2952.13,4.00,Salary Merit Increase,1l
1472,00477E744,A,NaN,Regular full time,N,7B,7,1-May-15,1.0,18-May-09,...,Off-cycle Promotion,1-Dec-14,4384.52,5.52,Salary Merit Increase,1-Jul-12,3782.37,5.00,Salary Merit Increase,4l
1473,06231F744,A,NaN,Regular full time,N,7A,7,1-Jun-14,2.0,30-Sep-10,...,Salary Merit Increase,1-Jun-14,14441.87,25.57,Backfill / Cascade Promot,1-Apr-14,1378.09,2.50,Salary Merit Increase,3l
1474,00128U744,A,NaN,Regular full time,N,6A,6,1-May-15,1.0,7-Apr-14,...,Salary Merit Increase,1-May-15,3375.88,15.00,Qualification,NaN,NaN,NaN,NaN,1l
1475,00901J744,A,NaN,Regular full time,N,6B,6,1-May-12,4.0,20-Jul-09,...,Salary Merit Increase,1-Apr-14,706.11,1.50,Salary Merit Increase,1-Oct-13,1766.96,3.90,Salary Merit Increase,1l
1476,03682P744,A,NaN,Regular full time,N,7A,7,16-Feb-15,1.3,16-Feb-15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,l
1477,37351744,A,NaN,Regular full time,N,7A,7,1-Aug-14,1.8,10-May-07,...,Salary Merit Increase,1-Aug-14,9881.67,18.08,Backfill / Cascade Promot,1-Apr-14,807.91,1.50,Salary Merit Increase,1l
1478,05285F744,A,NaN,Regular full time,N,7A,7,1-Jul-15,0.9,30-Aug-10,...,Salary Merit Increase,1-Jul-15,11843.15,27.06,Off-cycle Promotion,1-Oct-13,2123.43,5.10,Salary Merit Increase,1l
1479,0801B8744,A,NaN,Regular full time,N,6G,6,14-Sep-15,0.7,14-Sep-15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,l
1480,06965M744,A,NaN,Regular full time,N,6B,6,20-Jul-15,0.8,20-Jul-15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,l
1481,06570H744,A,NaN,Regular full time,N,6B,6,1-Apr-13,3.1,18-Oct-10,...,Salary Merit Increase,1-Apr-15,935.15,1.75,Salary Merit Increase,1-Dec-14,4857.92,10.00,Salary Merit Increase,1l
1482,02780F744,A,NaN,Regular full time,N,7B,7,1-Aug-15,0.8,24-Feb-10,...,Salary Merit Increase,1-Aug-15,15588.16,23.00,Off-cycle Promotion,1-Apr-15,1159.13,1.74,Salary Merit Increase,1l
1483,05215Q744,A,NaN,Regular full time,N,6B,6,5-Jun-15,1.0,5-Jun-15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,l
1484,02565S744,A,NaN,Regular full time,N,6B,6,1-Jan-16,0.4,29-May-12,...,Off-cycle Promotion,1-Jun-13,3375.88,15.00,Qualification,NaN,NaN,NaN,NaN,8l
1485,06663F744,A,NaN,Regular full time,N,7A,7,1-Feb-13,3.3,15-Nov-10,...,Salary Merit Increase,1-Apr-15,1176.17,1.74,Salary Merit Increase,1-Oct-13,2599.80,4.00,Salary Merit Increase,1l
1486,03466J744,A,NaN,Regular full time,N,7B,7,1-Nov-15,0.5,12-Apr-10,...,Off-cycle Promotion,1-Oct-13,2293.30,3.75,Salary Merit Increase,1-Jan-13,2050.07,3.47,Off-cycle Promotion,5l
1487,00570I744,A,NaN,Regular full time,N,6B,6,29-May-09,7.0,29-May-09,...,Salary Merit Increase,1-Apr-15,1286.73,2.49,Salary Merit Increase,1-Jul-12,2462.00,5.00,Salary Merit Increase,1l
1488,07568A744,A,NaN,Regular full time,N,7A,7,1-Jan-16,0.4,24-Dec-13,...,Off-cycle Promotion,1-Apr-15,1714.74,3.00,Salary Merit Increase,NaN,NaN,NaN,NaN,4l
1489,02252T744,A,NaN,Regular full time,N,6A,6,15-Oct-14,1.6,15-Oct-14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,l
1490,02735P744,A,NaN,Regular full time,N,6A,6,30-Nov-14,1.5,30-Nov-14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,l
1491,03293J744,A,NaN,Regular full time,N,6B,6,16-Jan-15,1.3,16-Jan-15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,l
1492,06663A744,A,NaN,Regular full time,N,7B,7,15-Nov-10,5.5,15-Nov-10,...,Salary Merit Increase,1-Apr-14,1088.82,1.01,Salary Merit Increase,1-Oct-13,5135.42,5.00,Salary Merit Increase,3l
1493,02220Q744,A,NaN,Regular full time,N,6B,6,14-Oct-14,1.6,14-Oct-14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,l
1494,07998W744,A,NaN,Regular full time,N,6G,6,14-Sep-15,0.7,14-Sep-15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,l
1495,03179P744,A,NaN,Regular full time,N,7A,7,5-Jan-15,1.4,5-Jan-15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,l
1496,797744,A,NaN,Regular full time,N,8,8,1-Jun-15,1.0,30-Aug-11,...,Off-cycle Promotion,1-Dec-14,3811.66,3.53,Salary Merit Increase,1-Jul-12,7533.44,7.50,Salary Merit Increase,4l
1497,71339744,A,NaN,Regular full time,Y,7B,7,1-Aug-11,4.8,4-Aug-08,...,Salary Merit Increase,1-Apr-15,2166.68,2.00,Salary Merit Increase,1-Dec-14,12868.72,13.48,Salary Merit Increase,2l

In [33]:
df_dict = df.T.to_dict().values()

In [35]:
# converting dict to numerics to using DictVectorizer to be accepted by numpy
vec = DictVectorizer()
# All values of sample.csv is put into the numpy array df_array
df_array = vec.fit_transform(df_dict).toarray()

In [36]:
df_array

array([[   0. ,    0. ,    0. , ...,  100. ,    0.5,    2.5],
       [   1. ,    0. ,    0. , ...,  100. ,    1.6,    1.6],
       [   0. ,    0. ,    0. , ...,  100. ,    0.2,    2. ],
       ...,
       [   0. ,    0. ,    0. , ...,  100. ,    1.4,    1.4],
       [   0. ,    0. ,    0. , ...,  100. ,    1. ,    4.7],
       [   0. ,    0. ,    0. , ...,  100. ,    4.8,    7.8]])

In [40]:
np.shape(df_array)

(1498, 7587)

In [ ]:
n_samples = 1498

In [44]:
# Create a classifier: a support vector classifier
classifier = svm.SVC(gamma=0.001)

In [ ]:
# We learn the digits on the first half of the digits
classifier.fit(df_array[:n_samples / 2], digits.target[:n_samples / 2])

In [12]:
#creating dict for categorical columns
colsCategorical = ['PBC 2013','PBC 2014','Salary increase reason 01','Salary Effective Date 02','Salary increase reason 02','Salary Effective Date 03','Salary increase reason 03',
]
cat_df =df[ colsCategorical ]
cat_dict = cat_df.T.to_dict().values()

In [26]:
# converting dict to numerics to using DictVectorizer to be accepted by numpy
vec = DictVectorizer()

#cat_array = vec.fit_transform(cat_dict).toarray()
cat_matrix = vec.fit_transform(cat_dict)

In [27]:
cat_matrix

<1498x123 sparse matrix of type '<class 'numpy.float64'>'
	with 10486 stored elements in Compressed Sparse Row format>

In [20]:
cat_num_df = pd.DataFrame(cat_df)

In [29]:
cat_num_df

,PBC 2013,PBC 2014,Salary increase reason 01,Salary Effective Date 02,Salary increase reason 02,Salary Effective Date 03,Salary increase reason 03
0,NaN,1,Off-cycle Promotion,1-Apr-15,Salary Merit Increase,1-Dec-14,Qualification
1,NaN,2,NaN,NaN,NaN,NaN,NaN
2,NaN,2,Off-cycle Promotion,1-Jan-16,Salary Merit Increase,NaN,NaN
3,NaN,2,Qualification,NaN,NaN,NaN,NaN
4,2,1,Salary Merit Increase,1-Dec-14,Salary Merit Increase,NaN,NaN
5,2+,2+,Salary Merit Increase,1-Apr-15,Salary Merit Increase,1-Dec-14,Salary Merit Increase
6,2,1,Salary Merit Increase,1-Oct-15,Salary Merit Increase,1-Jul-15,Off-cycle Promotion
7,NaN,NaN,Salary Merit Increase,NaN,NaN,NaN,NaN
8,NaN,2,NaN,NaN,NaN,NaN,NaN
9,3,2,Salary Merit Increase,1-Oct-13,Salary Merit Increase,1-Jul-12,Salary Merit Increase
10,1,2+,Salary Merit Increase,1-Jul-15,Off-cycle Promotion,1-Apr-15,Salary Merit Increase
11,NaN,2,Qualification,NaN,NaN,NaN,NaN
12,2,2,Salary Merit Increase,1-Dec-14,Salary Merit Increase,NaN,NaN
13,NaN,2,Off-cycle Promotion,NaN,NaN,NaN,NaN
14,2+,1,Off-cycle Promotion,1-Oct-15,Salary Merit Increase,1-Apr-15,Salary Merit Increase
15,NaN,2,Qualification,NaN,NaN,NaN,NaN
16,NaN,2,Qualification,NaN,NaN,NaN,NaN
17,2,2+,Salary Merit Increase,1-Apr-15,Salary Merit Increase,1-Dec-14,Salary Merit Increase
18,2,1,Off-cycle Promotion,1-Oct-15,Salary Merit Increase,1-Apr-15,Salary Merit Increase
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,2,Salary Merit Increase,1-Apr-14,Salary Merit Increase,NaN,NaN
21,2+,2+,Salary Merit Increase,1-Apr-15,Salary Merit Increase,1-Dec-14,Salary Merit Increase
22,2+,2,Salary Merit Increase,1-Apr-14,Salary Merit Increase,1-Sep-13,Qualification
23,2+,2+,Salary Merit Increase,1-Apr-15,Salary Merit Increase,1-Apr-14,Qualification
24,2+,1,Salary Merit Increase,1-Apr-15,Salary Merit Increase,1-Dec-14,Salary Merit Increase
25,2,2,Salary Merit Increase,1-Oct-13,Salary Merit Increase,1-Jul-12,Salary Merit Increase
26,NaN,NaN,Qualification,NaN,NaN,NaN,NaN
27,3,2+,Salary Merit Increase,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
1468,2+,1,Salary Merit Increase,1-Apr-15,Salary Merit Increase,1-Dec-14,Salary Merit Increase
1469,2,2,Salary Merit Increase,1-Jul-14,Off-cycle Promotion,1-Jul-12,Salary Merit Increase
1470,2+,2+,Off-cycle Promotion,1-Apr-15,Salary Merit Increase,1-Apr-14,Salary Merit Increase
1471,2,2,Salary Merit Increase,1-Dec-14,Salary Merit Increase,1-Oct-13,Salary Merit Increase
1472,2,2,Off-cycle Promotion,1-Dec-14,Salary Merit Increase,1-Jul-12,Salary Merit Increase
1473,1,2,Salary Merit Increase,1-Jun-14,Backfill / Cascade Promot,1-Apr-14,Salary Merit Increase
1474,NaN,2+,Salary Merit Increase,1-May-15,Qualification,NaN,NaN
1475,2+,2,Salary Merit Increase,1-Apr-14,Salary Merit Increase,1-Oct-13,Salary Merit Increase
1476,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1477,2+,2,Salary Merit Increase,1-Aug-14,Backfill / Cascade Promot,1-Apr-14,Salary Merit Increase
1478,2,2,Salary Merit Increase,1-Jul-15,Off-cycle Promotion,1-Oct-13,Salary Merit Increase
1479,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1480,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1481,2+,2+,Salary Merit Increase,1-Apr-15,Salary Merit Increase,1-Dec-14,Salary Merit Increase
1482,2,2+,Salary Merit Increase,1-Aug-15,Off-cycle Promotion,1-Apr-15,Salary Merit Increase
1483,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1484,2,2,Off-cycle Promotion,1-Jun-13,Qualification,NaN,NaN
1485,3,2+,Salary Merit Increase,1-Apr-15,Salary Merit Increase,1-Oct-13,Salary Merit Increase
1486,2,2,Off-cycle Promotion,1-Oct-13,Salary Merit Increase,1-Jan-13,Off-cycle Promotion
1487,2,2+,Salary Merit Increase,1-Apr-15,Salary Merit Increase,1-Jul-12,Salary Merit Increase
1488,NaN,1,Off-cycle Promotion,1-Apr-15,Salary Merit Increase,NaN,NaN
1489,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1490,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1491,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1492,2+,2,Salary Merit Increase,1-Apr-14,Salary Merit Increase,1-Oct-13,Salary Merit Increase
1493,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1494,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1495,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1496,2,2,Off-cycle Promotion,1-Dec-14,Salary Merit Increase,1-Jul-12,Salary Merit Increase
1497,1,2+,Salary Merit Increase,1-Apr-15,Salary Merit Increase,1-Dec-14,Salary Merit Increase

In [23]:
cat_array

array([[ nan,   0.,   0., ...,   0.,   0.,   0.],
       [ nan,   0.,   0., ...,   0.,   0.,   0.],
       [ nan,   0.,   0., ...,   0.,   0.,   0.],
       ...,
       [ nan,   0.,   0., ...,   0.,   0.,   0.],
       [  0.,   0.,   1., ...,   0.,   1.,   0.],
       [  0.,   1.,   0., ...,   0.,   1.,   0.]])

In [25]:
cat_array.interpolate()

AttributeError: 'numpy.ndarray' object has no attribute 'interpolate'